name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Setup Node.js (optional, only if you have JS build steps)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies (if you have any)
      # - name: Install Dependencies
      #   run: npm install

      # Build the site (if needed)
      # - name: Build Website
      #   run: npm run build

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Upload artifacts to GitHub Pages
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Deploy from the root directory

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
